import type { PropertyDefinition } from './api';

/**
 * Complete PBS property catalog — all 64 properties matching the backend
 * PROPERTY_DEFINITIONS and AA PBS at fapbs.aa.com.
 */
export const PROPERTY_DEFINITIONS: PropertyDefinition[] = [
  // Days Off (7)
  { key: 'maximize_total_days_off', category: 'days_off', label: 'Maximize Total Days Off', value_type: 'toggle', favorite: false },
  { key: 'minimize_days_off_between_blocks', category: 'days_off', label: 'Minimize Days Off between Work Blocks', value_type: 'integer', favorite: false },
  { key: 'maximize_weekend_days_off', category: 'days_off', label: 'Maximize Weekend Days Off', value_type: 'toggle', favorite: false },
  { key: 'maximize_block_of_days_off', category: 'days_off', label: 'Maximize Block of Days Off', value_type: 'toggle', favorite: false },
  { key: 'string_days_off_starting', category: 'days_off', label: 'String of Days Off Starting on Date', value_type: 'date', favorite: false },
  { key: 'string_days_off_ending', category: 'days_off', label: 'String of Days Off Ending on Date', value_type: 'date', favorite: false },
  { key: 'waive_minimum_days_off', category: 'days_off', label: 'Waive Minimum Days Off', value_type: 'toggle', favorite: false },
  // Line (18)
  { key: 'target_credit_range', category: 'line', label: 'Target Credit Range', value_type: 'time_range', favorite: true, aliases: ['pay', 'hours', 'money'] },
  { key: 'maximize_credit', category: 'line', label: 'Maximize Credit', value_type: 'toggle', favorite: false, aliases: ['pay', 'hours', 'money'] },
  { key: 'work_block_size', category: 'line', label: 'Work Block Size', value_type: 'int_range', favorite: false },
  { key: 'prefer_cadence_day_of_week', category: 'line', label: 'Prefer Cadence on Day-of-Week', value_type: 'days_of_week', favorite: false },
  { key: 'commutable_work_block', category: 'line', label: 'Commutable Work Block', value_type: 'toggle', favorite: false, aliases: ['commute', 'commuter'] },
  { key: 'pairing_mix_in_work_block', category: 'line', label: 'Pairing Mix in a Work Block', value_type: 'selection', favorite: false },
  { key: 'allow_double_up_on_date', category: 'line', label: 'Allow Double-Up on Date', value_type: 'date', favorite: false },
  { key: 'allow_double_up_by_range', category: 'line', label: 'Allow Double-Up by Range', value_type: 'date_range', favorite: false },
  { key: 'allow_multiple_pairings', category: 'line', label: 'Allow Multiple Pairings', value_type: 'toggle', favorite: false },
  { key: 'allow_multiple_pairings_on_date', category: 'line', label: 'Allow Multiple Pairings on Date', value_type: 'date', favorite: false },
  { key: 'allow_co_terminal_mix', category: 'line', label: 'Allow Co-Terminal Mix in Work Block', value_type: 'toggle', favorite: false },
  { key: 'clear_bids', category: 'line', label: 'Clear Bids', value_type: 'toggle', favorite: false },
  { key: 'waive_carry_over_credit', category: 'line', label: 'Waive Carry-Over Credit', value_type: 'toggle', favorite: false },
  { key: 'avoid_person', category: 'line', label: 'Avoid Person', value_type: 'text', favorite: false },
  { key: 'buddy_with', category: 'line', label: 'Buddy With', value_type: 'text', favorite: false },
  { key: 'waive_24hrs_rest_in_domicile', category: 'line', label: 'Waive 24 hrs rest in Domicile', value_type: 'toggle', favorite: false },
  { key: 'waive_30hrs_in_7_days', category: 'line', label: 'Waive 30 hrs in 7 Days', value_type: 'toggle', favorite: false },
  { key: 'waive_minimum_domicile_rest', category: 'line', label: 'Waive Minimum Domicile Rest', value_type: 'toggle', favorite: false },
  // Pairing (35 incl search-only)
  { key: 'report_between', category: 'pairing', label: 'Report Between', value_type: 'time_range', favorite: true },
  { key: 'release_between', category: 'pairing', label: 'Release Between', value_type: 'time_range', favorite: true },
  { key: 'prefer_pairing_type', category: 'pairing', label: 'Prefer Pairing Type', value_type: 'pairing_type', favorite: true },
  { key: 'co_terminal_satellite_airport', category: 'pairing', label: 'Co-Terminal/Satellite Airport', value_type: 'airport', favorite: true },
  { key: 'prefer_positions_order', category: 'pairing', label: 'Prefer Positions Order', value_type: 'position_list', favorite: true },
  { key: 'prefer_pairing_length', category: 'pairing', label: 'Prefer Pairing Length', value_type: 'integer', favorite: false, aliases: ['trip length', 'days', 'duration'] },
  { key: 'prefer_pairing_length_on_date', category: 'pairing', label: 'Prefer Pairing Length on Date', value_type: 'int_date', favorite: false },
  { key: 'prefer_duty_period', category: 'pairing', label: 'Prefer Duty Period', value_type: 'integer', favorite: false },
  { key: 'report_between_on_date', category: 'pairing', label: 'Report Between on Date', value_type: 'time_range_date', favorite: false },
  { key: 'release_between_on_date', category: 'pairing', label: 'Release Between on Date', value_type: 'time_range_date', favorite: false },
  { key: 'mid_pairing_report_after', category: 'pairing', label: 'Mid-Pairing Report After', value_type: 'time', favorite: false },
  { key: 'mid_pairing_release_before', category: 'pairing', label: 'Mid-Pairing Release Before', value_type: 'time', favorite: false },
  { key: 'max_tafb_credit_ratio', category: 'pairing', label: 'Maximum TAFB-credit ratio', value_type: 'decimal', favorite: false },
  { key: 'min_avg_credit_per_duty', category: 'pairing', label: 'Minimum Avg Credit per Duty', value_type: 'time', favorite: false },
  { key: 'max_duty_time_per_duty', category: 'pairing', label: 'Maximum Duty Time per Duty', value_type: 'time', favorite: false },
  { key: 'max_block_per_duty', category: 'pairing', label: 'Maximum Block per Duty', value_type: 'time', favorite: false },
  { key: 'min_connection_time', category: 'pairing', label: 'Minimum Connection Time', value_type: 'time', favorite: false },
  { key: 'max_connection_time', category: 'pairing', label: 'Maximum Connection Time', value_type: 'time', favorite: false },
  { key: 'prefer_deadheads', category: 'pairing', label: 'Prefer Deadheads', value_type: 'toggle', favorite: false, aliases: ['DH', 'dead head', 'positioning'] },
  { key: 'avoid_deadheads', category: 'pairing', label: 'Avoid Deadheads', value_type: 'toggle', favorite: false, aliases: ['DH', 'dead head', 'positioning'] },
  { key: 'layover_at_city', category: 'pairing', label: 'Layover at City', value_type: 'airport', favorite: false, aliases: ['destination', 'overnight', 'RON'] },
  { key: 'avoid_layover_at_city', category: 'pairing', label: 'Avoid Layover at City', value_type: 'airport', favorite: false, aliases: ['destination', 'overnight'] },
  { key: 'layover_at_city_on_date', category: 'pairing', label: 'Layover at City on Date', value_type: 'airport_date', favorite: false },
  { key: 'min_layover_time', category: 'pairing', label: 'Minimum Layover Time', value_type: 'integer', favorite: false },
  { key: 'max_layover_time', category: 'pairing', label: 'Maximum Layover Time', value_type: 'integer', favorite: false },
  { key: 'prefer_landing_at_city', category: 'pairing', label: 'Prefer Landing at City', value_type: 'airport', favorite: false },
  { key: 'avoid_landing_at_city', category: 'pairing', label: 'Avoid Landing at City', value_type: 'airport', favorite: false },
  { key: 'prefer_one_landing_first_duty', category: 'pairing', label: 'Prefer One Landing on First Duty', value_type: 'toggle', favorite: false },
  { key: 'prefer_one_landing_last_duty', category: 'pairing', label: 'Prefer One Landing on Last Duty', value_type: 'toggle', favorite: false },
  { key: 'max_landings_per_duty', category: 'pairing', label: 'Maximum Landing per Duty', value_type: 'integer', favorite: false },
  { key: 'prefer_aircraft', category: 'pairing', label: 'Prefer Aircraft', value_type: 'equipment', favorite: false, aliases: ['equipment', 'plane', 'fleet', '777', '737', '321'] },
  { key: 'avoid_aircraft', category: 'pairing', label: 'Avoid Aircraft', value_type: 'equipment', favorite: false, aliases: ['equipment', 'plane', 'fleet'] },
  { key: 'prefer_language', category: 'pairing', label: 'Prefer Language', value_type: 'text', favorite: false },
  { key: 'prefer_positions_order_per_aircraft', category: 'pairing', label: 'Prefer Positions Order per Aircraft', value_type: 'text', favorite: false },
  { key: 'pairing_id', category: 'pairing', label: 'Pairing ID', value_type: 'text', favorite: false },
  // Reserve (4)
  { key: 'waive_carryover_days_off', category: 'reserve', label: 'Waive Carryover Days Off', value_type: 'toggle', favorite: false },
  { key: 'block_of_reserve_days_off', category: 'reserve', label: 'Block of Reserve Days Off', value_type: 'integer', favorite: false },
  { key: 'reserve_day_of_week_off', category: 'reserve', label: 'Reserve Day of Week Off', value_type: 'days_of_week', favorite: false },
  { key: 'reserve_work_block_size', category: 'reserve', label: 'Reserve Work Block Size', value_type: 'int_range', favorite: false },
];

export const FAVORITE_PROPERTIES = new Set([
  'target_credit_range',
  'report_between',
  'release_between',
  'prefer_pairing_type',
  'co_terminal_satellite_airport',
  'prefer_positions_order',
]);
